blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [   
    path('blog/', views.PostListView.as_view(), name='blog_list'),
    path('blog/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('tag/<str:tag_name>/', views.PostListByTagView.as_view(), name='post_by_tag'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cotizaciones/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import handler404


urlpatterns=[
    
    path('cotizaciones',views.list, name='cotizaciones'),
    path('idi/', views.Check_idi.list_idi , name='idi'),
    path('idi/ver/<int:id>/', views.Check_idi.read_check, name='verIdi'),
    path('idi/editar/<int:id>', views.Check_control.update_check, name='editarIdi'),
    path('create', views.Check_control.create_check , name='create'),
    path('editar/<int:id>', views.Check_control.update_check, name='editar'),
    path('ver/<int:id>/', views.Check_control.read_check, name='ver'),
    path('delete/<int:id>/', views.Check_control.delete, name='delete'),
    path('pdf/<int:pk>/', views.PdfView.as_view(), name='pdf'),
    path('renovaciones/<int:id>', views.renovaciones, name='renovar'),
    path('register/', views.register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
   

]

cotizador/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cotizaciones.urls')),
    path('', include('vendedores.urls')),
    path('', include('clientes.urls')),
    path('', include('productos.urls')),
    path('', include('empresas.urls')),
    path('', include('deals.urls')),
    path('', include('sitioweb.urls')),
    path('', include('blog.urls')),
    path('', include('assistant.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clientes/models.py
from django.db import models
from django.contrib.auth.models import User



class ContactForm(models.Model):
    nombre = models.CharField(max_length=255)
    email = models.EmailField()
    empresa = models.CharField(max_length=255, blank=True)  # Opcional, puede ser dejado en blanco
    telefono = models.CharField(max_length=20, blank=True)  # Opcional, puede ser dejado en blanco
    mensaje = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)  # Se registra automáticamente al crear un objeto

    def __str__(self):
        return f"{self.nombre} - {self.email}"



class Cliente(models.Model):
    ETAPAS = [
        ('inicial', 'Inicial'),
        ('primer_contacto', 'Primer Contacto'),
        ('seguimiento', 'Seguimiento'),
        ('propuesta_enviada', 'Propuesta Enviada'),
        ('cerrado', 'Cerrado'),
        ('perdido', 'Perdido'),
        ('es_cliente', 'Es cliente'),
    ]

    nombre = models.CharField(max_length=255)
    mail = models.EmailField()
    telefono = models.CharField(max_length=15)
    empresa = models.CharField(max_length=255, null=True, blank=True)
    asunto=models.CharField(max_length=255, null=True, blank=True)
    posicion = models.CharField(max_length=255, null=True, default='Desconocido')
    etapa = models.CharField(max_length=50, choices=ETAPAS, default='inicial')

    def __str__(self):
        return f"{self.nombre} - {self.etapa}"
    

deals/models.py
from django.db import models
from django.contrib.auth.models import User


class Deal(models.Model):
    STATUS_CHOICES = [
        ('nuevo', 'Nuevo'),
        ('en_progreso', 'En Progreso'),
        ('ganado', 'Ganado'),
        ('perdido', 'Perdido'),
    ]

    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    value = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='nuevo')
    empresa = models.ForeignKey('empresas.Empresa', on_delete=models.CASCADE, null=True, blank=True)  # En el futuro podría ser una ForeignKey a Empresa
    cliente = models.ForeignKey('clientes.Cliente', on_delete=models.CASCADE, null=True, blank=True)  
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    owner = models.ManyToManyField(User, null=True)

    def __str__(self):
        return self.title

empresas/models.py
from django.db import models

# Create your models here.
class Empresa(models.Model):
    nombre = models.CharField(max_length=255)
    categoria = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)
    direccion = models.CharField(max_length=255)
    telefono = models.CharField(max_length=15)
    sitio_web = models.URLField(blank=True, null=True)
    

    def __str__(self):
        return self.nombre

cotizaciones/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import Check, Status, Comentarios
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
    )


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de usuario'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de usuario'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirmar contraseña'}),
             }



class CheckForm(forms.ModelForm):
    class Meta: 
        
    
        model = Check
        fields='__all__'


         # Etiqueta opcional para la opción vacía)

class ComentariosForm(forms.ModelForm):
    class Meta:
        model=Comentarios
        fields=[

            'resuelto',
            'comentario',
        ]

cotizaciones/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from .models import Check, Categoria, Comentarios
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from .forms import LoginForm, CheckForm, ComentariosForm, CustomUserCreationForm
from django.template.loader import get_template
from django.templatetags.static import static
from django.http import HttpResponse, request, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib import messages



#weasy HTML to PDF 
import functools

from cotizador.wsgi import *
from cotizador import settings


#HTML2PDF

import os
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.template.loader import get_template, render_to_string
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders


#Intentar llenar el Check desde json 
from django.views.decorators.csrf import csrf_exempt
import json



#CRUD Usuario Gerente

class Check_control(LoginRequiredMixin):   # Esto permite solicitudes POST sin un token CSRF (útil para API)
    @csrf_exempt
    def create_check(request):
            if request.method == 'POST':
                try:
                    # Intentamos cargar los datos JSON enviados en la solicitud
                    data = json.loads(request.body)

                    # Rellenamos el formulario con los datos del JSON
                    form = CheckForm(data=data)

                    if form.is_valid():
                        # Si el formulario es válido, asignamos el autor (el usuario actual)
                       
                        form.save()

                        # Retornamos una respuesta de éxito con el id del nuevo registro
                        return JsonResponse({'message': 'Check created successfully!', 'id': form.instance.id}, status=201)
                    else:
                        # Si el formulario no es válido, devolvemos los errores
                        return JsonResponse({'errors': form.errors}, status=400)

                except json.JSONDecodeError:
                    # Si no se pudo parsear el JSON, devolvemos un error
                    return JsonResponse({'error': 'Invalid JSON'}, status=400)

            else:
                return JsonResponse({'error': 'Invalid request method'}, status=405)
    


    def read_check(request, id):
        check=get_object_or_404(Check, id=id,  autor_id=request.user)
        comentarios=Comentarios.objects.filter(check_asociado=check.id)
        form2=ComentariosForm(data=request.POST)
        if form2.is_valid():
             form2.instance.autor_comentario = request.user
             form2.instance.check_asociado = check
             form2.save()
        context ={
                  'check':check,
                  'form2': form2,
                  'comentarios': comentarios,
        }

        return render(request, 'cotizaciones/view.html', context)
    
    

    def update_check(request, id):
        check=get_object_or_404(Check, id=id, autor_id=request.user)
        comentarios=Comentarios.objects.filter(check_asociado=check.id)
        form=CheckForm(instance=check)
        form2=ComentariosForm()
        context ={
                  'check':check,
                  'comentarios': comentarios,
                  'form':form,
                  'form2':form2, 
        }
        if request.method=='POST': 
            form=CheckForm(data=request.POST, instance=check)
            form2=ComentariosForm(data=request.POST)
            if form2.is_valid():
                form2.instance.autor_comentario = request.user
                form2.instance.check_asociado = check
                form2.save()
            if form.is_valid():
                form.instance.autor = request.user
                form.save()

             #Después debe redirigir a la lista de checks creados 
        else:
            print('No es valido')
            form=CheckForm(instance=check) 
        
        return render(request, 'cotizaciones/edit.html', context)





    @login_required
    def delete(request, id):
        check=get_object_or_404(Check, id=id, autor_id=request.user)
        check.delete()
        return redirect('cotizaciones')

#Vistas


#CRUD Usuario IDI 

class Check_idi(LoginRequiredMixin): 

    def read_check(request, id):
        check=get_object_or_404(Check, id=id)
        comentarios=Comentarios.objects.filter(check_asociado=check.id)
        form2=ComentariosForm(data=request.POST)
        if form2.is_valid():
             form2.instance.autor_comentario = request.user
             form2.instance.check_asociado = check
             form2.save()
        context ={
                  'check':check,
                  'form2': form2,
                  'comentarios': comentarios,
        }

        return render(request, 'cotizaciones/view.html', context)
    
    

    def update_check(request, id):
        check=get_object_or_404(Check, id=id)
        comentarios=Comentarios.objects.filter(check_asociado=check.id)
        form=CheckForm(instance=check)
        form2=ComentariosForm()
        context ={
                  'check':check,
                  'comentarios': comentarios,
                  'form':form,
                  'form2':form2, 
        }
        if request.method=='POST': 
            form=CheckForm(data=request.POST, instance=check)
            form2=ComentariosForm(data=request.POST)
            if form2.is_valid():
                form2.instance.autor_comentario = request.user
                form2.instance.check_asociado = check
                form2.save()
            if form.is_valid():
                form.instance.autor = request.user
                form.save()

             #Después debe redirigir a la lista de checks creados 
        else:
            print('No es valido')
            form=CheckForm(instance=check) 
        
        return render(request, 'cotizaciones/edit.html', context)
    
    def list_idi(request): 
        if request.user.is_authenticated:
            check=Check.objects.all()
            #related_check=Check.objects.filter(autor_id=request.user)
            context ={
                    'check':check,
                    #'related_check': related_check,
                    
            }
            for obj in check:
                obj.verificar_expiracion()
                obj.save
            return render (request, 'cotizaciones/list_idi.html', {'check': check})
        else: 
            return redirect('/accounts/login/')




#Para filtrar los checks por usuario
def list(request): 
    if request.user.is_authenticated:
        #check=Check.objects.all()
        check=Check.objects.filter(autor_id=request.user)
        context ={
                  'check':check,
                  #'related_check': related_check,
                   
        }
        for obj in check:
             obj.verificar_expiracion()
             obj.save
        return render (request, 'cotizaciones/list.html', {'check': check})
    else: 
         return redirect('/accounts/login/')


        




#Renovaciones
def renovaciones(request, id ):
    check=Check.objects.filter(id=id)
    if request.method=='POST':
        for obj in check: 
             obj.renovar_expiracion()
             print('exitoso')
        return render (request, 'cotizaciones/renew.html', {'check': check})
    else: 
        return render (request, 'cotizaciones/renew.html', {'check': check})

    
     
def renovar(request, id):
    check=Check.objects.filter(vigente=False, id=id)
    if request.method=='POST':
        for obj in check: 
             obj.renovar_expiracion()
             obj.save
        return render (request, 'cotizaciones/renew.html', {'check': check})
    else: 
         return redirect('cotizaciones')
     
     


def unsecure(request):   
    return render(request,"unsecure.html",{})  


def secure(request):   
    return render(request,"secure.html",{})


def register(request):
    data= {
            'form' : CustomUserCreationForm()     
        }
    if request.method == 'POST':    
        user_creation_form=CustomUserCreationForm(data=request.POST)
        if user_creation_form.is_valid(): 
            user_creation_form.save()
            user=authenticate(username=user_creation_form.cleaned_data['username'], password=user_creation_form.cleaned_data['password1'])
            login(request, user)
            return redirect ('cotizaciones')
    return render(request, 'registration/register.html', data)
        
    




    



class PdfView(View): 
    
    def link_callback(uri, rel):
            
    #        Convert HTML URIs to absolute system paths so xhtml2pdf can access those
     #       resources

            result = finders.find(uri)
            if result:
                    if not isinstance(result, (list, tuple)):
                            result = [result]
                    result = list(os.path.realpath(path) for path in result)
                    path=result[0]
            else:
                    sUrl = settings.STATIC_URL        # Typically /static/
                    sRoot = settings.STATIC_ROOT      # Typically /home/userX/project_static/
                    mUrl = settings.MEDIA_URL         # Typically /media/
                    mRoot = settings.MEDIA_ROOT       # Typically /home/userX/project_static/media/

                    if uri.startswith(mUrl):
                            path = os.path.join(mRoot, uri.replace(mUrl, ""))
                    elif uri.startswith(sUrl):
                            path = os.path.join(sRoot, uri.replace(sUrl, ""))
                    else:
                            return uri

            # make sure that file exists
            if not os.path.isfile(path):

cotizaciones/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>{% block title %}Administrador{% endblock %}</title>
    

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
{% load static %}
    <link rel="stylesheet" href="{% static 'cotizaciones/css/sidemenu.css' %}">

    {% block extra_css %}
    <!-- Lugar para CSS adicional en otras plantillas -->
    {% endblock %}
</head>
<body>
 
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Mayapack</h3>
            </div>
            <ul class="list-unstyled components">
                <p>Creacion de checks</p>
                
               
                <li>
                    <a href="{% url 'cliente_list'  %}">Clientes</a>
                </li>


                
                 <li>
                    <a href="{% url 'cotizaciones'  %}">Cotizaciones</a>
                </li>
                 <li>
                    <a href="{% url 'empresa_list'  %}">Empresas</a>
                </li>
                 <li>
                    <a href="{% url 'cliente_list'  %}">Clientes</a>
                </li>
                 <li>
                    <a href="{% url 'deal_list'  %}">Negocios</a>
                </li>
                 <li>
                    <a href="{% url 'producto_list'  %}">Productos</a>
                </li>
                <li>
                    <a href="{% url 'vendedor_list'  %}">Vendedores</a>
                </li>
               
                <!--<li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                       
                    </ul>
                </li>
                <li>
                    <a href="#">Portfolio</a>
                </li>-->
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
            
            
            <ul class="list-unstyled CTAs">
                <form method="POST" action="{% url 'logout' %}">
            {% csrf_token %}
            <button  class="btn btn-primary" type="submit">logout</button>
         
            <li class="article"><a href="{% url 'login'%}?next={{request.path}}">Iniciar sesión</a></li>
                </form>
            </ul>
            

          

            <!--<ul class="list-unstyled CTAs">
                <li>
                    <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>
                </li>
                <li>
                    <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>
                </li>
            </ul>-->
        </nav>

        
        {% block content %}
        <!-- Contenido principal aquí -->
        {% endblock %}
    </div>
    



    
    <!-- Bootstrap JS y dependencias -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
    {% block extra_js %}

    
    <!-- Lugar para JS adicional en otras plantillas -->
    {% endblock %}
</body>
</html>

cotizaciones/templates/create_css.html
{% extends 'base.html' %}


{% block title %}Create{% endblock %}

{% load static %}
 {% block extra_css %}
<link rel="stylesheet" href="{% static 'check/css/create.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css">
{% endblock %}
{% block content %}

<form method="post">
              {% csrf_token %}
              {{form.as_p}}
              <button type="submit" class="btn btn-secondary mb-3">Guardar</button>
          </form>


{% endblock %}

    {% block extra_js %}
        <script src="{% static 'check/js/create.js' %}"></script>
       <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
       <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
    {% endblock %}

cotizaciones/templates/edit_prueba.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World</title>
</head>
<body>
    <div class="container mt-5">
        <h1>Checks</h1>
        <div>       
        <form action= "{% url 'create' %}" method='post'>
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Crear nuevo Check</button>
        </form>
        </div>
    
    </div>
</body>
</html>

cotizaciones/templates/login copy.html
<!-- login.html -->
{% extends '../registration/base.html' %}


{% block title %}Login{% endblock %}

{% block content %}
{% load static %}
 {% if form.errors %}
    <p>Su nombre de usuario y contraseña no coinciden. Inténtalo de nuevo.</p>
  {% endif %}

 

  <form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <table>
      <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
      </tr>
      <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
      </tr>
    </table>
    <input type="submit" value="login">
    <input type="hidden" name="next" value="{{ next }}">
  </form>

  {# Asume que configura la vista de restablecimiento de contraseña en su URLconf #}
  <p><a href="{% url 'password_reset' %}">¿Olvidó su contraseña?</a></p>

{% endblock %}

cotizaciones/templates/navbar.html
<!-- templates/navbar.html -->
<style>
        .sidebar {
            height: 100vh;
            background-color: #abb9e8;
            color: white;
            position: fixed;
            width: 200px;
        }
        .sidebar a {
            color: white;
            text-decoration: none;
            padding: 10px;
            display: block;
        }
        .sidebar a:hover {
            background-color: #8e9ddf;
        }
        .sidebar .sidebar-header {
            padding: 15px;
            display: flex;
            align-items: center;
        }
        .sidebar .sidebar-header img {
            width: 40px;
            height: 40px;
            margin-right: 10px;
        }
        .sidebar .sidebar-header .fa-user-circle {
            margin-left: auto;
            cursor: pointer;
        }
    </style>
 
 
 
 <div class="sidebar">
        <div class="sidebar-header">
            <img src="/static/logo.png" alt="Logo">
            <span>Mi Proyecto</span>
            <i class="fa fa-user-circle" title="Editar Perfil"></i>
        </div>
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'deal_list' %}"><i class="fa fa-handshake"></i> Deals</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'empresa_list' %}"><i class="fa fa-building"></i> Empresas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cliente_list' %}"><i class="fa fa-users"></i> Clientes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cotizaciones' %}"><i class="fa fa-file-invoice"></i> Cotizaciones</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}"><i class="fa fa-sign-in-alt"></i> Inicio de Sesión</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-sign-out-alt"></i> Cerrar Sesión</a>
            </li>
        </ul>
    </div>